apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: datapower-apiconnect-gw
spec:
  version: 10.5-lts
  license:
    accept: true
  replicas: 1
  users:
  - name: admin
    passwordSecret: admin-credentials
    accessLevel: privileged
