apiVersion: analytics.apiconnect.ibm.com/v1beta1
kind: AnalyticsCluster
metadata:
  name: analytics
spec:
  storage:
    type: shared
    shared:
      volumeClaimTemplate:
        storageClassName: ibmc-vpc-block-10iops-tier