apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-connect-operator
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  labels:
    group: applications
spec:
  project: default
  source:
    path: 'components/api-connect-operator/base'
  destination:
    server: https://kubernetes.default.svc
    namespace: apic
  syncPolicy:
    automated:
      selfHeal: true
