apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-connect-operator
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: default
  source:
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/apic-remote-gw.git
    targetRevision: HEAD
    path: 'components/api-connect-operator/base'
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      selfHeal: true
