apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  labels:
    group: applications
spec:
  project: default
  source:
    path: 'components/cert-manager/base'
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
