apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datapower
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: default
  source:
    repoURL: https://github.com/Nordic-MVP-GitOps-Repos/apic-remote-gw.git
    targetRevision: HEAD
    path: 'components/datapower/base'
  destination:
    server: https://kubernetes.default.svc
    namespace: datapower
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
