apiVersion: gateway.apiconnect.ibm.com/v1beta1
kind: GatewayCluster
metadata:
  name: gateway-cluster
spec:
  additionalDomainConfig:
    - certs:
        - certType: usrcerts
          secret: apimanager-ca
      dpApp:
        config:
          - gwd-add-apimgmt-ca
      name: apiconnect
  adminUser:
    secretName: admin-credentials
  apicGatewayPeeringTLS:
    secretName: gateway-peering
  apicGatewayServiceTLS:
    secretName: gateway-service
  apicGatewayServiceV5CompatibilityMode: false
  gatewayEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: >-
          gw.HOST
        secretName: gateway-cluster-endpoint
    ingressClassName: REPLACED_BY_KUSTOMIZE_PATCH
  gatewayManagerEndpoint:
    annotations:
      cert-manager.io/issuer: ingress-issuer
    hosts:
      - name: >-
          gwd.HOST
        secretName: gateway-cluster-manager-endpoint
    ingressClassName: REPLACED_BY_KUSTOMIZE_PATCH
  imageRegistry: cp.icr.io/cp/apic
  imagePullSecrets:
    - ibm-entitlement-key
  profile: n1xc4.m8
  syslogConfig:
    enabled: false
  tokenManagementService:
    enabled: true
    storage:
      storageClassName: REPLACED_BY_KUSTOMIZE_PATCH
      volumeSize: 30Gi