apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: datapower
spec:
  version: 10.5-lts
  license:
    accept: true
    use: developers-limited
    license: L-RJON-CCAT6P
  replicas: 1
