apiVersion: gateway.apiconnect.ibm.com/v1beta1
kind: GatewayCluster
metadata:
  name: gateway-cluster
spec:
  gatewayEndpoint:
    ingressClassName: nginx
  gatewayManagerEndpoint:
    ingressClassName: nginx
